x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/retroassembly.svg

services:
  retroassembly:
    image: arianrhodsandlot/retroassembly:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${RETROASSEMBLY_PORT_1:-8080}:8080"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - retroassembly-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  retroassembly-config:
