x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/vaultwarden.svg

services:
  vaultwarden:
    image: vaultwarden/server:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${VAULTWARDEN_PORT_1:-8086}:8086"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - vaultwarden-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  vaultwarden-config:
