x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/monica.svg

services:
  monica:
    image: monica:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${MONICA_PORT_1:-8088}:8088"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - monica-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  monica-config:
