x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/emby.svg

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${EMBY_PORT_1:-8096}:8096"
      - "${EMBY_PORT_2:-8920}:8920"
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - emby-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  emby-config:
