x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/dozzle.svg

services:
  dozzle:
    image: amir20/dozzle:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${DOZZLE_PORT_1:-8081}:8081"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - dozzle-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  dozzle-config:
