x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/transmission.svg

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${TRANSMISSION_PORT_1:-9091}:9091"
      - "${TRANSMISSION_PORT_2:-51413}:51413"
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - transmission-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  transmission-config:
