x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/sonarr.svg

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${SONARR_PORT_1:-8989}:8989"
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - sonarr-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  sonarr-config:
