x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/caddy.svg

services:
  caddy:
    image: caddy:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-8088}:8088"
      - "${CADDY_HTTPS_PORT:-8443}:443"
      - "${CADDY_ADMIN_PORT:-2019}:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
volumes:
  caddy-data:
  caddy-config:
