x-arcane:
  icon: https://moratac.github.io/moratac-arcane-registry/icons/wallos.svg

services:
  wallos:
    image: bellamy/wallos:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "${WALLOS_PORT_1:-8282}:8282"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - wallos-config:/config
      - ${DATA_PATH:-./data}:/data
volumes:
  wallos-config:
